{{- if .Values.vault_settings.aws_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.vault_settings.aws_secret_manager_region }}
    objects: |
      - objectName: "workflow-manager-db-user"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "workflow-manager-db-password"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "db-host"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "workflow-manager-db"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "message-broker-driver"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "message-broker-connection-string"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_workflow_manager.secretName }}
      type: Opaque
      data:
        - objectName: "workflow-manager-db-user"
          key: workflow-manager-db-user
        - objectName: "workflow-manager-db-password"
          key: workflow-manager-db-password
        - objectName: "db-host"
          key: db-host
        - objectName: "workflow-manager-db"
          key: workflow-manager-db
        - objectName: "message-broker-driver"
          key: message-broker-driver
        - objectName: "message-broker-connection-string"
          key: message-broker-connection-string
{{- end }}
