secrets:
  workflow_manager_database:
    secretName: workflow-manager-database
  keycloak_certs_endpoint:
    secretName: keycloak-certs-endpoint
  common_secret:
    secretName: common-secret
  rabbitmq_password:
    secretName: rabbitmq-password
  security_certs:
    secretName: security-certs
  kafka_secrets:
    secretName: kafka-secrets
  database_ssl_secret:
    secretName: database-ssl-secret
  deps_workflow_manager:
    secretName: deps-workflow-manager
  telemetry_secrets:
    secretName: telemetry-secrets

helm_logs_job:
  serviceAccountName: gitlab-ci
  image:
    path: "/base/kubernetes-helm"
    pullPolicy: IfNotPresent
    tag: "0.1.1"
  resources: {}

registry: ""
env: ""

workflow_manager:
  replicaCount: 1
  image:
    path: "/deps-dev-x01/deps-workflow-manager-api"
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: artifactory
  service:
    type: ClusterIP
    port: 8000
  resources: {}
  #    limits:
  #      cpu: 200m
  #      memory: 800Mi
  #    requests:
  #      cpu: 100m
  #      memory: 350Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

workflow_manager_dispatcher:
  replicaCount: 1
  image:
    path: "/deps-dev-x01/deps-workflow-manager-api"
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: artifactory
  resources: {}
  #    limits:
  #      cpu: 100m
  #      memory: 850Mi
  #    requests:
  #      cpu: 80m
  #      memory: 600Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

certs_location:
  certs_default_path: "/tmp/ssl"
  database_sslcerts_path: "/home/dbcerts"

workflow_manager_settings:
  ENV: dev

  DATABASE_PORT: '5432'
  DATABASE_DIALECT: postgresql
  DATABASE_DRIVER: psycopg2
  DATABASE_REQUIRE_SECURE_TRANSPORT: false
  DATABASE_SSLKEY_PATH: "/home/dbcerts/tls.key"
  DATABASE_SSLCERT_PATH: "/home/dbcerts/tls.crt"
  DATABASE_SSLROOTCERT_PATH: "/home/dbcerts/root.crt"

  # Priority (seconds)
  PRIORITY_MEDIUM_BOUNDARY: '3600'
  PRIORITY_HIGH_BOUNDARY: '10800'

  # Auth
  AUTH_VERIFY_SSL: false

  # File Blob storage service
  FILE_STORAGE_URL: 'http://file-storage-nginx:8000/api/storage/v1/file'
  FILE_STORAGE_EXTERNAL_URL: 'https://dev-host/api/storage/v1/file'
  DOCUMENT_TYPE_SERVICE_URL: 'http://document-type:8000'
  TEMPLATE_SERVICE_URL: 'http://template:8000'
  DOCUMENT_SERVICE_URL: 'http://backend:8000'
  EXTRACTION_SERVICE_URL: "http://extraction:8000"

  LOG_LEVEL: "INFO"
  DOCUMENTATION_ENABLED: true

  # RabbitMQ
  RABBITMQ_TLS_ENABLED: false
  RABBITMQ_TLS_DLX_PER_QUEUE: false

  KAFKA_GROUP_ID: workflow-manager
  KAFKA_SECURITY_ENABLED: false

  VERSION_CLASSIFICATION_ENABLED: false
  CLASSIFICATION_ENABLED: false
  VALIDATION_ENABLED: false
  # Azure Service Bus
  ASB_SUBSCRIPTION_STRATEGY: 'no_preparation'
  ASB_TOPIC_NAME: 'deps-topic'
  message_broker_asb_without_manage_permission: false

  # Telemetry
  INSTRUMENTATION_ENABLED: false
  SERVICE_NAME: deps-workflow-manager
  EXPORTER_TYPE: azure

helm:
  enabled: false

csi:
  csi_default_name: deps-workflow-manager
  vault_namespace: 'k8s-dev'
  roleName: 'k8s-dev'
  vaultKubernetesMountPath: 'kubernetes-dev'

secrets_location:
  secrets_default_path: "/mnt/secrets-store"

service_account:
  serviceAccountName: 'deps-develop'

secret_project_id:
  id: ""

azure_kv_settings:
  keyvaultName: ""
  tenantId: ""
  userAssignedIdentityID: ""
  resourceGroup: ""
  subscriptionId: ""

vault_settings:
  enabled: false
  hashicorp_vault: false
  azure_key_vault: false
  gcp_secret_manager: false
  aws_secret_manager: false
  aws_secret_manager_region: ''

workflow_manager_dispatcher_vault_enabled:
  env:
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: deps-workflow-manager
        key: db-host
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: deps-workflow-manager
        key: workflow-manager-db-user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: deps-workflow-manager
        key: workflow-manager-db-password
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: deps-workflow-manager
        key: workflow-manager-db
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: deps-workflow-manager
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: deps-workflow-manager
        key: message-broker-connection-string

workflow_manager_dispatcher_vault_disabled:
  env:
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: database-host
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: workflow-manager-database
        key: user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: workflow-manager-database
        key: password
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: workflow-manager-database
        key: database-db
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-connection-string

workflow_manager_vault_enabled:
  env:
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: deps-workflow-manager
        key: db-host
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: deps-workflow-manager
        key: workflow-manager-db-user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: deps-workflow-manager
        key: workflow-manager-db-password
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: deps-workflow-manager
        key: workflow-manager-db
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: deps-workflow-manager
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: deps-workflow-manager
        key: message-broker-connection-string

workflow_manager_vault_disabled:
  env:
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: workflow-manager-database
        key: user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: workflow-manager-database
        key: password
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: workflow-manager-database
        key: database-db
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: database-host
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-connection-string
