apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-manager-api-configmap
  labels:
    {{- include "deps-workflow-manager.labels" . | nindent 4 }}
data:
  ENV: {{ .Values.workflow_manager_settings.ENV }}
  DATABASE_PORT: '{{ .Values.workflow_manager_settings.DATABASE_PORT }}'
  DATABASE_DIALECT: {{ .Values.workflow_manager_settings.DATABASE_DIALECT }}
  DATABASE_DRIVER: {{ .Values.workflow_manager_settings.DATABASE_DRIVER }}
  DATABASE_REQUIRE_SECURE_TRANSPORT: '{{ .Values.workflow_manager_settings.DATABASE_REQUIRE_SECURE_TRANSPORT }}'
  {{ if .Values.workflow_manager_settings.DATABASE_REQUIRE_SECURE_TRANSPORT }}
  DATABASE_SSLKEY: {{ .Values.workflow_manager_settings.DATABASE_SSLKEY_PATH }}
  DATABASE_SSLCERT: {{ .Values.workflow_manager_settings.DATABASE_SSLCERT_PATH }}
  DATABASE_SSLROOTCERT: {{ .Values.workflow_manager_settings.DATABASE_SSLROOTCERT_PATH }}
  {{ end }}

  AUTH_VERIFY_SSL: '{{ .Values.workflow_manager_settings.AUTH_VERIFY_SSL }}'

  FILE_STORAGE_URL: '{{ .Values.workflow_manager_settings.FILE_STORAGE_URL }}'
  FILE_STORAGE_EXTERNAL_URL: '{{ .Values.workflow_manager_settings.FILE_STORAGE_EXTERNAL_URL }}'
  DOCUMENT_TYPE_SERVICE_URL: '{{ .Values.workflow_manager_settings.DOCUMENT_TYPE_SERVICE_URL }}'
  TEMPLATE_SERVICE_URL: '{{ .Values.workflow_manager_settings.TEMPLATE_SERVICE_URL }}'
  DOCUMENT_SERVICE_URL: '{{ .Values.workflow_manager_settings.DOCUMENT_SERVICE_URL }}'
  EXTRACTION_SERVICE_URL: '{{ .Values.workflow_manager_settings.EXTRACTION_SERVICE_URL }}'

  LOG_LEVEL: '{{ .Values.workflow_manager_settings.LOG_LEVEL }}'
  DOCUMENTATION_ENABLED: '{{ .Values.workflow_manager_settings.DOCUMENTATION_ENABLED }}'
  KAFKA_GROUP_ID: '{{ .Values.workflow_manager_settings.KAFKA_GROUP_ID }}'
  RABBITMQ_TLS_DLX_PER_QUEUE: '{{ .Values.workflow_manager_settings.RABBITMQ_TLS_DLX_PER_QUEUE }}'
  VERSION_CLASSIFICATION_ENABLED: '{{ .Values.workflow_manager_settings.VERSION_CLASSIFICATION_ENABLED }}'
  CLASSIFICATION_ENABLED: '{{ .Values.workflow_manager_settings.CLASSIFICATION_ENABLED }}'
  VALIDATION_ENABLED: '{{ .Values.workflow_manager_settings.VALIDATION_ENABLED }}'
  {{ if .Values.workflow_manager_settings.RABBITMQ_TLS_ENABLED }}
  RABBITMQ_TLS_HOST: '{{ .Values.workflow_manager_settings.RABBITMQ_TLS_HOST }}'
  RABBITMQ_TLS_PORT: '{{ .Values.workflow_manager_settings.RABBITMQ_TLS_PORT }}'
  RABBITMQ_TLS_USER: '{{ .Values.workflow_manager_settings.RABBITMQ_TLS_USER }}'
  RABBITMQ_TLS_VHOST: '{{ .Values.workflow_manager_settings.RABBITMQ_TLS_VHOST }}'
  RABBITMQ_TLS_SUBJECT: '{{ .Values.workflow_manager_settings.RABBITMQ_TLS_SUBJECT }}'
  RABBITMQ_TLS_CA_CERT: '{{ .Values.workflow_manager_settings.RABBITMQ_TLS_CA_CERT }}'
  RABBITMQ_TLS_CLIENT_CERT: '{{ .Values.workflow_manager_settings.RABBITMQ_TLS_CLIENT_CERT }}'
  RABBITMQ_TLS_CLIENT_KEY: '{{ .Values.workflow_manager_settings.RABBITMQ_TLS_CLIENT_KEY }}'
  {{ end }}
  {{ if .Values.workflow_manager_settings.KAFKA_SECURITY_ENABLED }}
  KAFKA_SASL_MECHANISM: '{{ .Values.workflow_manager_settings.KAFKA_SASL_MECHANISM }}'
  KAFKA_SECURITY_PROTOCOL: '{{ .Values.workflow_manager_settings.KAFKA_SECURITY_PROTOCOL }}'
  {{ end }}
  {{ if .Values.workflow_manager_settings.message_broker_asb_without_manage_permission }}
  ASB_SUBSCRIPTION_STRATEGY: '{{ .Values.workflow_manager_settings.ASB_SUBSCRIPTION_STRATEGY }}'
  {{ end }}
  ASB_TOPIC_NAME: '{{ .Values.workflow_manager_settings.ASB_TOPIC_NAME }}'

  # Telemetry
  INSTRUMENTATION_ENABLED: '{{ .Values.workflow_manager_settings.INSTRUMENTATION_ENABLED }}'
  SERVICE_NAME: '{{ .Values.workflow_manager_settings.SERVICE_NAME }}'
  EXPORTER_TYPE: '{{ .Values.workflow_manager_settings.EXPORTER_TYPE }}'
