apiVersion: v1
kind: Service
metadata:
  name: workflow-manager
  labels:
    {{- include "deps-workflow-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.workflow_manager.service.type }}
  ports:
    - port: {{ .Values.workflow_manager.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "deps-workflow-manager.selectorLabels" . | nindent 4 }}
