workflow_manager:
  image:
    path: "/deps-platform/deps-workflow-manager-api"
  resources: {}

workflow_manager_dispatcher:
  image:
    path: "/deps-platform/deps-workflow-manager-api"
  resources: {}

migrator:
  image:
    path: "/deps-platform/deps-workflow-manager-migrator"

workflow_manager_settings:
  ENV: other
  FILE_STORAGE_URL: 'http://file-storage-nginx:8000/api/storage/v1/file'
  FILE_STORAGE_EXTERNAL_URL: 'https://other-host/api/storage/v1/file'

  DATABASE_DB: workflow-manager-other
  DATABASE_REQUIRE_SECURE_TRANSPORT: false

  LOG_LEVEL: "INFO"

migration_settings:
  DATABASE_DB: workflow-manager-other
  DATABASE_REQUIRE_SECURE_TRANSPORT: false

helm:
  enabled: false
