workflow_manager:
  image:
    path: "/deps-presale-x01/deps-workflow-manager-api"
    pullPolicy: Always
  resources: {}

workflow_manager_dispatcher:
  image:
    path: "/deps-presale-x01/deps-workflow-manager-api"
    pullPolicy: Always
  resources: {}

migrator:
  image:
    path: "/deps-presale-x01/deps-workflow-manager-migrator"
    pullPolicy: Always

workflow_manager_settings:
  ENV: presale
  FILE_STORAGE_URL: 'http://file-storage-nginx:8000/api/storage/v1/file'
  FILE_STORAGE_EXTERNAL_URL: 'https://presale-host/api/storage/v1/file'

  DATABASE_DB: workflow-manager-presale
  DATABASE_REQUIRE_SECURE_TRANSPORT: false

  LOG_LEVEL: "INFO"

migration_settings:
  DATABASE_DB: workflow-manager-presale
  DATABASE_REQUIRE_SECURE_TRANSPORT: false

helm:
  enabled: false

csi:
  vault_namespace: 'k8s-presale'
  roleName: 'k8s-presale'
  vaultKubernetesMountPath: 'kubernetes-presale'

service_account:
  serviceAccountName: 'deps-presale'
