workflow_manager:
  image:
    path: "/deps-platform/deps-workflow-manager-api"
  resources: {}
#    limits:
#      cpu:
#      memory:
#    requests:
#      cpu:
#      memory:

workflow_manager_dispatcher:
  image:
    path: "/deps-platform/deps-workflow-manager-api"
  resources: {}
#    limits:
#      cpu:
#      memory:
#    requests:
#      cpu:
#      memory:

migrator:
  image:
    path: "/deps-platform/deps-workflow-manager-migrator"

workflow_manager_settings:
  ENV: perf
  FILE_STORAGE_URL: 'http://file-storage-nginx:8000/api/storage/v1/file'
  FILE_STORAGE_EXTERNAL_URL: 'https://perf-host/api/storage/v1/file'

  DATABASE_DB: deps-workflow-manager-ds
  DATABASE_REQUIRE_SECURE_TRANSPORT: false

  LOG_LEVEL: "INFO"

migration_settings:
  DATABASE_DB: deps-workflow-manager-ds
  DATABASE_REQUIRE_SECURE_TRANSPORT: false

helm:
  enabled: false
