workflow_manager:
  image:
    path: "/deps-platform/deps-workflow-manager-api"
  resources: {}
#    limits:
#      cpu:
#      memory:
#    requests:
#      cpu:
#      memory:

workflow_manager_dispatcher:
  image:
    path: "/deps-platform/deps-workflow-manager-api"
  resources: {}
#    limits:
#      cpu:
#      memory:
#    requests:
#      cpu:
#      memory:

migrator:
  image:
    path: "/deps-platform/deps-workflow-manager-migrator"

workflow_manager_settings:
  ENV: qa
  FILE_STORAGE_URL: 'http://file-storage-nginx:8000/api/storage/v1/file'
  FILE_STORAGE_EXTERNAL_URL: 'https://qa-host/api/storage/v1/file'

  DATABASE_REQUIRE_SECURE_TRANSPORT: false

  LOG_LEVEL: "INFO"

  # Telemetry
  INSTRUMENTATION_ENABLED: true

migration_settings:
  DATABASE_REQUIRE_SECURE_TRANSPORT: false

helm:
  enabled: false

csi:
  vault_namespace: 'k8s-qa'
  roleName: 'k8s-qa'
  vaultKubernetesMountPath: 'kubernetes-qa'

service_account:
  serviceAccountName: 'deps-qa'
